name: FreeRDP_Hardcoded_Token_hoanhanhvunick1

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999 # Thời gian chờ tối đa

    steps:
    # Bước 1: Tải Ngrok và các file cần thiết (TRỪ start.bat)
    - name: Download Ngrok and supporting files
      shell: powershell
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        # Tải loop.ps1 từ kho của bạn
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/loop.ps1 -OutFile loop.ps1
        # Tải wallpaper nếu cần
        # Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/wallpaper.jpg -OutFile wallpaper.jpg
        # Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/wallpaper.bat -OutFile wallpaper.bat

    # Bước 2: Giải nén Ngrok
    - name: Extract Ngrok Files
      run: Expand-Archive ngrok.zip -DestinationPath .
      shell: powershell

    # ---- Bước 3: Cấu hình token Ngrok (NHÚNG TRỰC TIẾP - CẢNH BÁO BẢO MẬT!) ----
    - name: Configure Ngrok Authtoken (WARNING: Insecure Hardcoded Token)
      # !!! CẢNH BÁO NGHIÊM TRỌNG: Token Ngrok của bạn bị lộ trong code này !!!
      shell: cmd # Hoặc powershell, cả hai đều chạy được lệnh này
      run: .\ngrok.exe authtoken 2wJOyBLBh4cMau6pWvzMKVgbA3H_gfM4VLsnY57s6GFJ4ztm
      # Không cần khối 'env:' khi token được nhúng trực tiếp
    # -----------------------------------------------------------------------------

    # Bước 4: Kích hoạt RDP
    - name: Activating RDP access
      shell: powershell
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        # Copy wallpaper nếu cần
        # copy wallpaper.jpg D:\a\wallpaper.jpg
        # copy wallpaper.bat D:\a\wallpaper.bat

    # Bước 5: Tạo Tunnel Ngrok chạy nền
    - name: Create Ngrok Tunnel in Background
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok.exe tcp 3389"'
      shell: powershell

    # Bước 6: Chờ Ngrok khởi động
    - name: Wait for Ngrok potentially start
      run: Start-Sleep -Seconds 25
      shell: powershell

    # Bước 7: Chạy Script cài đặt (Nội dung start.bat KHÔNG kiểm tra Ngrok)
    - name: Run Setup Script Inline (No Ngrok Check)
      shell: cmd
      run: |
        @echo off
        echo Starting basic setup script (inline)...
        del /f "C:\Users\Public\Desktop\Epic Games Launcher.lnk" > out.txt 2>&1
        net config server /srvcomment:"Windows Server RDP via Workflow" > out.txt 2>&1
        REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer" /V EnableAutoTray /T REG_DWORD /D 0 /F > out.txt 2>&1
        REM REG ADD "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" /f /v Wallpaper /t REG_SZ /d .\wallpaper.bat
        echo Setting up user account...
        net user administrator JohnTech1234 /add >nul
        net localgroup administrators administrator /add >nul
        net user administrator /active:yes >nul
        net user installer /delete >nul 2>&1
        echo Configuring system...
        diskperf -Y >nul
        sc config Audiosrv start= auto >nul
        sc start Audiosrv >nul
        ICACLS C:\Windows\Temp /grant administrator:F >nul
        ICACLS C:\Windows\installer /grant administrator:F >nul
        echo Basic setup complete.
        echo.
        echo --- RDP Connection Information ---
        echo IMPORTANT: Get the IP Address and Port from your Ngrok Dashboard:
        echo            >> https://dashboard.ngrok.com/endpoints/status <<
        echo.
        echo Username: administrator
        echo Password: JohnTech1234
        echo ----------------------------------
        echo.
        echo You should be able to connect via RDP using the info above.

    # Bước 8: Chạy vòng lặp giữ kết nối (QUAN TRỌNG!)
    - name: Start Keep Alive Loop (IMPORTANT)
      run: .\loop.ps1
      shell: powershell
