name: FreeRDP_Download_StartScript_hoanhanhvunick1

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999 # Thời gian chờ tối đa

    steps:
    # Bước 1: Tải Ngrok và các file cần thiết TỪ KHO CỦA BẠN
    - name: Download Ngrok and required scripts from hoanhanhvunick1/rdpaa
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        # Tải start.bat (phiên bản đã sửa lỗi mà bạn vừa cập nhật vào kho)
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/start.bat -OutFile start.bat
        # Tải loop.ps1
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/loop.ps1 -OutFile loop.ps1
        # Tải wallpaper nếu cần
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/wallpaper.jpg -OutFile wallpaper.jpg
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/wallpaper.bat -OutFile wallpaper.bat
      shell: powershell

    # Bước 2: Giải nén Ngrok
    - name: Extract Ngrok Files
      run: Expand-Archive ngrok.zip -DestinationPath .
      shell: powershell

    # Bước 3: Cấu hình token Ngrok (Nhúng trực tiếp - CẢNH BÁO BẢO MẬT!)
    - name: Configure Ngrok Authtoken (WARNING: Insecure Hardcoded Token)
      # !!! CẢNH BÁO: Token nhúng trực tiếp vào code là rủi ro bảo mật !!!
      run: .\ngrok.exe authtoken 2wJOyBLBh4cMau6pWvzMKVgbA3H_gfM4VLsnY57s6GFJ4ztm
      shell: cmd # Chạy file .exe bằng cmd

    # Bước 4: Kích hoạt RDP
    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
      shell: powershell

    # Bước 5: Tạo Tunnel Ngrok chạy nền
    - name: Create Ngrok Tunnel in Background
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok.exe tcp 3389"'
      shell: powershell

    # Bước 6: Chờ Ngrok khởi động (Khuyến nghị)
    - name: Wait for Ngrok initialization
      run: Start-Sleep -Seconds 25
      shell: powershell

    # Bước 7: Chạy file start.bat ĐÃ TẢI VỀ (Phiên bản sửa lỗi từ kho của bạn)
    - name: Run Setup Script (start.bat from hoanhanhvunick1/rdpaa)
      # Chạy file start.bat đã tải ở Bước 1
      run: cmd /c start.bat
      shell: cmd

    # Bước 8: Chạy vòng lặp giữ kết nối (QUAN TRỌNG!)
    - name: Start Keep Alive Loop (IMPORTANT)
      # Chạy script loop.ps1 đã tải về từ kho của bạn
      run: .\loop.ps1
      shell: powershell
