name: FreeRDP_From_hoanhanhvunick1_Repo

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999 # Cân nhắc giảm nếu không cần thiết

    steps:
    # Bước 1: Tải Ngrok và các file từ kho hoanhanhvunick1/rdpaa
    - name: Download Ngrok and scripts from hoanhanhvunick1/rdpaa
      # Sử dụng Powershell làm shell mặc định cho bước này
      shell: powershell
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        # --- THAY ĐỔI LINK TẠI ĐÂY ---
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/wallpaper.jpg -OutFile wallpaper.jpg
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/wallpaper.bat -OutFile wallpaper.bat
        # --- KẾT THÚC THAY ĐỔI LINK ---

    # Bước 2: Giải nén Ngrok
    - name: Extract Ngrok Files
      # Giải nén vào thư mục hiện tại (.)
      run: Expand-Archive ngrok.zip -DestinationPath .
      shell: powershell

    # Bước 3: Kết nối tài khoản Ngrok dùng GitHub Secrets (Cách an toàn)
    - name: Connecting to your Ngrok account using Secrets
      # Chạy ngrok.exe từ thư mục hiện tại
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      # Sử dụng shell cmd để chạy file exe và truy cập biến môi trường
      shell: cmd
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    # Bước 4: Kích hoạt RDP
    - name: Activating RDP access
      # Sử dụng Powershell
      shell: powershell
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        # Kiểm tra xem start.bat có thực sự cần các file này ở D:\a không
        # Nếu không chắc, có thể copy vào thư mục hiện tại (.) thay thế
        # copy wallpaper.jpg .
        # copy wallpaper.bat .
        copy wallpaper.jpg D:\a\wallpaper.jpg
        copy wallpaper.bat D:\a\wallpaper.bat

    # Bước 5: Tạo Tunnel Ngrok chạy nền
    - name: Creating Tunnel
      # Chạy trong Powershell riêng
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok.exe tcp 3389"'
      shell: powershell

    # Bước 6: Chờ Ngrok khởi động (Rất khuyến khích thêm bước này)
    - name: Wait for Ngrok initialization
      run: Start-Sleep -Seconds 25 # Chờ 25 giây
      shell: powershell

    # Bước 7: Chạy start.bat (từ kho của bạn)
    - name: Connecting to your RDP (Running start.bat)
      # Chạy file start.bat đã tải về
      run: cmd /c start.bat
      shell: cmd

    # Bước 8: Tải và chạy loop.ps1 để giữ kết nối (QUAN TRỌNG)
    - name: RDP is ready! Start Keep Alive loop.
      # Sử dụng Powershell
      shell: powershell
      run: |
        # --- THAY ĐỔI LINK TẠI ĐÂY ---
        Invoke-WebRequest https://github.com/hoanhanhvunick1/rdpaa/raw/main/loop.ps1 -OutFile loop.ps1
        # --- KẾT THÚC THAY ĐỔI LINK ---
        # Chạy loop.ps1 từ thư mục hiện tại
        .\loop.ps1
