name: FreeRDP_From_hoanhanhvunick1_Repo_Debug_Ngrok

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    # Giảm timeout khi đang debug
    timeout-minutes: 30

    steps:
    # Bước 1: Tải file
    - name: Download Ngrok and required scripts from hoanhanhvunick1/rdpaa
      shell: powershell
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/start.bat -OutFile start.bat # Đảm bảo file này có mã hóa ANSI
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/loop.ps1 -OutFile loop.ps1
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/wallpaper.jpg -OutFile wallpaper.jpg
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/wallpaper.bat -OutFile wallpaper.bat

    # Bước 2: Giải nén Ngrok
    - name: Extract Ngrok Files
      run: Expand-Archive ngrok.zip -DestinationPath .
      shell: powershell

    # Bước 3: Kết nối tài khoản Ngrok
    - name: Connecting to your Ngrok account using Secrets
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      shell: cmd
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    # Bước 4: Kích hoạt RDP
    - name: Activating RDP access
      shell: powershell
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        # copy wallpaper.jpg D:\a\wallpaper.jpg # Comment out khi debug
        # copy wallpaper.bat D:\a\wallpaper.bat # Comment out khi debug

    # ---- Bước 5: CHẠY NGORK TRỰC TIẾP ĐỂ DEBUG ----
    - name: DEBUG - Run Ngrok Directly
      shell: cmd # Sử dụng cmd để chạy trực tiếp và xem output
      run: |
        echo "Attempting to start Ngrok directly..."
        .\ngrok.exe tcp 3389 -log=stdout -log-level=debug
        echo "Ngrok command finished (or failed). Check output above."
        # Bước này sẽ bị block ở đây nếu Ngrok chạy thành công
        # Hoặc sẽ hiển thị lỗi nếu Ngrok thất bại

    # ---- CÁC BƯỚC SAU SẼ KHÔNG CHẠY NẾU NGORK BLOCK Ở TRÊN ----
    # Bạn có thể comment out các bước này khi đang debug Ngrok
    # - name: Wait for Ngrok initialization
    #   run: Start-Sleep -Seconds 5 # Chỉ cần chờ ngắn nếu chạy trực tiếp
    #   shell: powershell

    # - name: Run Setup Script (start.bat)
    #   run: cmd /c start.bat
    #   shell: cmd

    # - name: Start Keep Alive Loop (IMPORTANT)
    #   run: .\loop.ps1
    #   shell: powershell
