name: FreeRDP_From_hoanhanhvunick1

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999 # Cẩn thận với timeout quá dài

    steps:
    - name: Download Ngrok and required scripts from hoanhanhvunick1/rdpaa
      run: |
        # Tải Ngrok (link này không đổi)
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        # Tải các file từ kho hoanhanhvunick1/rdpaa
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/loop.ps1 -OutFile loop.ps1
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/wallpaper.jpg -OutFile wallpaper.jpg
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/wallpaper.bat -OutFile wallpaper.bat
      shell: powershell

    - name: Extract Ngrok Files
      run: Expand-Archive ngrok.zip -DestinationPath .
      shell: powershell

    - name: Configure Ngrok Authtoken (WARNING: Insecure Hardcoded Token)
      # !!! CẢNH BÁO BẢO MẬT !!! Token được nhúng trực tiếp.
      # Nên sử dụng GitHub Secrets thay thế.
      run: .\ngrok.exe authtoken 2wJOyBLBh4cMau6pWvzMKVgbA3H_gfM4VLsnY57s6GFJ4ztm
      shell: cmd # Sử dụng cmd để chạy ngrok.exe

    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        # Sao chép wallpaper nếu cần thiết bởi start.bat hoặc wallpaper.bat
        # Đường dẫn D:\a thường là thư mục gốc của runner trong Actions, cần kiểm tra lại nếu script yêu cầu đường dẫn khác
        # copy wallpaper.jpg D:\a\wallpaper.jpg
        # copy wallpaper.bat D:\a\wallpaper.bat
      shell: powershell

    - name: Create Ngrok Tunnel in Background
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok.exe tcp 3389"'
      shell: powershell

    - name: Wait for Ngrok initialization
      run: Start-Sleep -Seconds 20 # Chờ Ngrok khởi động
      shell: powershell

    - name: Run Setup Script (start.bat from hoanhanhvunick1/rdpaa)
      # Chạy script start.bat tải từ kho mới.
      # Đảm bảo nội dung start.bat trong kho mới là chính xác và không cần jq.
      # Kiểm tra địa chỉ RDP trên dashboard Ngrok.
      run: cmd /c start.bat
      shell: cmd

    - name: Start Keep Alive Loop (IMPORTANT)
      # Chạy script loop.ps1 tải từ kho mới để giữ runner hoạt động.
      run: ./loop.ps1
      shell: powershell # loop.ps1 là script PowerShell
