name: FreeRDP_From_hoanhanhvunick1_Repo_With_Ngrok_Logging

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    # Bước 1: Tải Ngrok và các file từ kho hoanhanhvunick1/rdpaa
    - name: Download Ngrok and required scripts from hoanhanhvunick1/rdpaa
      shell: powershell
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/start.bat -OutFile start.bat # Đảm bảo file này có mã hóa ANSI
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/loop.ps1 -OutFile loop.ps1
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/wallpaper.jpg -OutFile wallpaper.jpg
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/wallpaper.bat -OutFile wallpaper.bat

    # Bước 2: Giải nén Ngrok
    - name: Extract Ngrok Files
      run: Expand-Archive ngrok.zip -DestinationPath .
      shell: powershell

    # Bước 3: Kết nối tài khoản Ngrok dùng GitHub Secrets
    - name: Connecting to your Ngrok account using Secrets
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      shell: cmd
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    # Bước 4: Kích hoạt RDP
    - name: Activating RDP access
      shell: powershell
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.jpg D:\a\wallpaper.jpg # Xem lại đường dẫn nếu cần
        copy wallpaper.bat D:\a\wallpaper.bat # Xem lại đường dẫn nếu cần

    # ---- Bước 5: SỬA ĐỔI ĐỂ GHI LOG NGORK ----
    - name: Creating Tunnel and Logging Ngrok Output
      shell: powershell
      run: |
        # Chạy ngrok và chuyển hướng output/error vào file log
        # Không dùng Start-Process nữa, chạy trực tiếp trong nền của shell hiện tại
        # Dùng Start-Job để chạy nền tốt hơn trong PowerShell
        Start-Job -ScriptBlock { .\ngrok.exe tcp 3389 *> ngrok_combined.log }

    # Bước 6: Chờ Ngrok khởi động và ghi log
    - name: Wait for Ngrok initialization
      run: Start-Sleep -Seconds 20 # Giảm thời gian chờ một chút vì chạy trực tiếp
      shell: powershell

    # ---- Bước 7: THÊM BƯỚC KIỂM TRA LOG NGORK ----
    - name: Display Ngrok Logs
      shell: powershell
      # Lấy Job vừa chạy nền, chờ nó một chút rồi lấy output (nếu có)
      # Quan trọng: Lấy nội dung file log mà ngrok ghi vào
      run: |
        echo "--- Checking Ngrok Process ---"
        Get-Process ngrok -ErrorAction SilentlyContinue
        echo "--- Displaying ngrok_combined.log ---"
        Get-Content .\ngrok_combined.log -ErrorAction SilentlyContinue

    # Bước 8: Chạy start.bat (từ kho của bạn)
    - name: Connecting to your RDP (Running start.bat)
      run: cmd /c start.bat
      shell: cmd

    # Bước 9: Tải và chạy loop.ps1 để giữ kết nối
    - name: RDP is ready! Start Keep Alive loop.
      shell: powershell
      run: |
        # Đảm bảo loop.ps1 đã được tải ở bước 1
        # Invoke-WebRequest https://github.com/hoanhanhvunick1/rdpaa/raw/main/loop.ps1 -OutFile loop.ps1
        .\loop.ps1
