name: FreeRDP_From_hoanhanhvunick1_Repo_Fixed_Token

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999 # Thời gian chờ tối đa

    steps:
    # Bước 1: Tải Ngrok và các file cần thiết TỪ KHO CỦA BẠN
    - name: Download Ngrok and required scripts from hoanhanhvunick1/rdpaa
      shell: powershell
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        # Tải start.bat (Đảm bảo file này trong kho của bạn đã sửa lỗi jq VÀ có mã hóa ANSI)
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/start.bat -OutFile start.bat
        # Tải loop.ps1
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/loop.ps1 -OutFile loop.ps1
        # Tải wallpaper nếu cần
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/wallpaper.jpg -OutFile wallpaper.jpg
        Invoke-WebRequest https://raw.githubusercontent.com/hoanhanhvunick1/rdpaa/main/wallpaper.bat -OutFile wallpaper.bat

    # Bước 2: Giải nén Ngrok
    - name: Extract Ngrok Files
      run: Expand-Archive ngrok.zip -DestinationPath .
      shell: powershell

    # ---- Bước 3: SỬA LỖI SHELL Ở ĐÂY ----
    - name: Connecting to your Ngrok account using Secrets (Fixed Shell)
      # Sử dụng shell: powershell để hiểu cú pháp $Env:
      shell: powershell
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    # ------------------------------------

    # Bước 4: Kích hoạt RDP
    - name: Activating RDP access
      shell: powershell
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        # Xem lại đường dẫn copy nếu cần thiết cho start.bat/wallpaper.bat
        copy wallpaper.jpg D:\a\wallpaper.jpg
        copy wallpaper.bat D:\a\wallpaper.bat

    # Bước 5: Tạo Tunnel Ngrok chạy nền (Quay lại dùng Start-Process)
    - name: Create Ngrok Tunnel in Background
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok.exe tcp 3389"'
      shell: powershell

    # Bước 6: Chờ Ngrok khởi động
    - name: Wait for Ngrok initialization
      run: Start-Sleep -Seconds 25 # Chờ 25 giây
      shell: powershell

    # Bước 7: Chạy start.bat (từ kho của bạn - phiên bản đã sửa lỗi & mã hóa ANSI)
    - name: Run Setup Script (start.bat)
      run: cmd /c start.bat
      shell: cmd

    # Bước 8: Chạy vòng lặp giữ kết nối (QUAN TRỌNG!)
    - name: Start Keep Alive Loop (IMPORTANT)
      run: .\loop.ps1
      shell: powershell
